#!/usr/bin/python3

from bottle import route, run, request#, static_file, abort
import json
from os import getuid
from threading import Thread

import libaqueduct as aqueduct



conf = aqueduct.config()



@route('/', method='GET')
def get_info():
	info = {
		'service': 'aqueduct-server',
		'name': conf['name'],
		'version': conf['version']
		}
	return json.dumps(info)



@route('/submit', method='POST')
def build_submit():
	upload = request.files.data

	if not upload or not upload.file:
		return {'success': False, 'message': 'No file supplied'}

	upload.save(conf['dir']['intake'])

	#t = Thread(target=builder.pkg_build, args=(buildid,os,release,path_to_source,))
	#t.start()

	return {
			'success': True,
			'message': 'Source submitted',
			}



if getuid() == 0:
	run(host='', port=conf['port'], debug=True)
else:
	print('Please run aqueduct-server as root')
