#!/usr/bin/python3

from os import listdir, path, popen
import aqueduct



def deb_exists(directory, name, version, arch):
	return path.exists(directory + '/' + name + '_' + version + '_' + arch + '.deb')



directory = "/home/vallery/Desktop/conduit/aqueduct/aqueduct-queue"
config = aqueduct.config()
aptly = aqueduct.repo_deb(config)

for os in config.releases:
	for release in config.releases[os]:
		for component in config.releases[os][release]['components']:
			aptly.create(release, component)



for f in listdir(directory):
	name, version = f.split('_', 1)
	if version.endswith('.tar.gz'):
		version = version[:-7] #Strip the extention

		if deb_exists(directory, name, version, 'all'):
			print(name)
		elif all(deb_exists(directory, name, version, arch) for arch in config.releases[os][release]['arch']):
			print(name + " exists in all formats")
			#aptly.add(, 
