#!/usr/bin/python3

import sftp

from sys import argv
from configparser import ConfigParser



host = argv[1]

config = ConfigParser()
config.read('/home/vallery/.aqueduct-send.conf')
if host in config.sections():
	if config[host]['method'] == 'sftp':
		sftp.upload(config[host]['domain'], 'vallery', '/home/vallery', ['/home/vallery/Pictures/87128.jpg'])
