#!/usr/bin/python3

from bottle import route, run, request#, static_file, abort
import json
from os import getuid
from threading import Thread

import libaqueduct as aqueduct



conf = aqueduct.config()



@route('/', method='GET')
def get_info():
	info = {
		'service': 'aqueduct-server',
		'version': conf.general['version']
		}
	return json.dumps(info)



@route('/submit', method='POST')
def build_submit():
	upload = request.files.data

	if not upload or not upload.file:
		return {'success': False, 'message': 'No file supplied'}

	upload.save(conf.general['dir']['intake'])

	t = Thread(target=aqueduct.intake, args=(path_to_source,))
	t.start()

	return {
		'success': True,
		'message': 'Source submitted'
	}



if getuid() == 0:
	run(host='', port=conf.general['port'], debug=True)
else:
	print('Please run aqueduct-server as root')
